name: Deploy to Hetzner

on:
  push:
    branches:
      - main
      - zeeshan-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Hetzner & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ "${{ github.ref_name }}" == "main" ]; then
              TARGET_DIR="/root/raidr-backend-prod"
            else
              TARGET_DIR="/root/raidr-backend"
            fi
            
            echo "Deploying branch ${{ github.ref_name }} to $TARGET_DIR"
            cd $TARGET_DIR
            git pull origin ${{ github.ref_name }}
            docker compose up -d --build
